import uuid

from marspylib.yama.model import MarsMetadata, Molecule
from marspylib.yama.uid import (
    METADATA_UID_LENGTH,
    _base58_encode,
    new_metadata_uid,
    new_molecule_uid,
)

# uid -> expected Base58 encoding, generated by the real Java library
# (com.chrylis:base58-codec, via mars-core's MarsMath.getUUID58()) and
# cross-checked byte-for-byte -- see tests/yama/fixtures/java-harness/GenUID.java.
JAVA_VECTORS = [
    ("00000000-0000-0000-0000-000000000000", "1"),   # all-zero -> single "1", not empty/padded
    ("00000000-0000-0000-0000-000000000001", "2"),
    ("00ffffff-ffff-ffff-ffff-ffffffffffff", "8apgaUT7n92zWZMWcMJUp"),  # leading zero byte -> shorter output
    ("ffffffff-ffff-ffff-ffff-ffffffffffff", "xBuEXKpA6iqZQK5Kf2TnkV"),
    ("80000000-0000-0000-0000-000000000000", "gNKktSGN3DHuVnxnC1WFEY"),
    ("5c9f20d5-8361-b331-eed8-a921eac80778", "crn7iWkXz1qx4XYBhqXedm"),
    ("d545798e-09a4-ef89-5393-ea7f1fea4064", "sktahJ9kSChKyjJccxYAMs"),
    ("3c4b499b-090b-c6fa-595f-9fb9fcf0e5bc", "8rQejWW7cr1k4RaEBvTnoC"),
    ("72b5373b-e9f1-db2d-a35d-fdc91d9763e0", "faxLPbhCSxrLPwPHDDNz9d"),
    ("288427c5-ee03-f47e-c4d5-d909433cfccf", "61bub1MrfEKST5ePRFG3Qp"),
]


def test_matches_real_java_base58_encoding():
    for uid_str, expected in JAVA_VECTORS:
        got = _base58_encode(uuid.UUID(uid_str).bytes)
        assert got == expected, f"{uid_str}: expected {expected!r}, got {got!r}"


def test_alphabet_excludes_confusing_characters():
    from marspylib.yama.uid import _ALPHABET
    for confusing in "0OIl":
        assert confusing not in _ALPHABET


def test_new_molecule_uid_is_unique_and_nonempty():
    uids = {new_molecule_uid() for _ in range(200)}
    assert len(uids) == 200
    assert all(uid for uid in uids)


def test_new_metadata_uid_is_fixed_length():
    for _ in range(50):
        uid = new_metadata_uid()
        assert len(uid) == METADATA_UID_LENGTH == 10


def test_molecule_gets_auto_uid_when_not_specified():
    mol1 = Molecule()
    mol2 = Molecule()
    assert mol1.uid and mol2.uid
    assert mol1.uid != mol2.uid


def test_molecule_respects_explicit_uid():
    mol = Molecule(uid="my-custom-uid")
    assert mol.uid == "my-custom-uid"


def test_metadata_gets_auto_uid_of_correct_length():
    meta = MarsMetadata()
    assert len(meta.uid) == METADATA_UID_LENGTH


def test_metadata_respects_explicit_uid():
    meta = MarsMetadata(uid="my-custom-meta-uid")
    assert meta.uid == "my-custom-meta-uid"
